name: Update Kubernetes Pod

on:
  push:
    branches:
      - main

jobs:
  update-kube-pod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f C:/docker_art/deployment
