apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-db-data-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Change this if needed based on your requirements
  resources:
    requests:
      storage: 1Gi  # Adjust the storage size as per your needs
