name: Deploy to Kubernetes on Docker Desktop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Deployment
        run: |
          kubectl apply -f deployment/secrets.yaml
          kubectl apply -f deployment/deployment.yaml
          kubectl apply -f deployment/service.yaml
          kubectl apply -f deployment/ingress.yaml
          kubectl apply -f deployment/hpa.yaml
          kubectl apply -f deployment/pvc.yaml
          kubectl apply -f deployment/pv.yaml
          kubectl apply -f deployment/docker-desktop-config.yaml