name: Deploy to Kubernetes on Docker Desktop

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Deployment Script
        run: |
          kubectl apply -f deployment/deployment.yaml