name: Update Kubernetes Pods

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy to K8s
        run: kubectl apply -f deployment/deployment.yaml