name: Update Kubernetes Pods

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/kubectl
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push myersben9/brigart:latest
      
      - name: Decode kubeconfig secret
        run: |
          echo "${{ secrets.kube_config }}" | base64 --decode > kubeconfig.yaml

      - name: Update Kubernetes deployment
        run: |
          KUBECONFIG=./kubeconfig.yaml kubectl set image deployment/brig-art-container-bc6f4cdfc-tcjg6 brig-art-container=myersben9/brigart:latest
