name: Update Kubernetes Pods

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Build and push Docker image
        run: |
          docker build -t myersben9/brigart:latest .
          docker push myersben9/brigart:latest
      - name: Create kubeconfig
        run: |
          mkdir ${HOME}/.kube
          echo ${{ secrets.KUBE_CONFIG }} | base64 --decode > ${HOME}/.kube/config
          cat ${HOME}/.kube/config
      - name: Use context
        run: kubectl config use-context docker-desktop
      - name: Deploy to K8s
        run: kubectl apply -f deployment/ --validate=false